[package]
name = "line-counter"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
thiserror = "2.0.12"

[dev-dependencies]
tempfile = "3.8"
criterion = "0.5"

[[bench]]
name = "benchmark"
harness = false
